server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
         locator:
            enabled: true
      routes:
        - id: microservice-one
          uri: http://localhost:8081/
          Predicates:
            - Path=/api/microservice-one/**

eureka:
  client:
     service-url:
       defaultZone: http://localhost:8761/eureka/
     instance:
       prefer-ip-address: true